export const ADD_COUNTER_PRODUCT = "ADD_COUNTER_PRODUCT"
export const SUBSTRACT_COUNTER_PRODUCT = "SUBSTRACT_COUNTER_PRODUCT"
export const ADD_TO_CART = "ADD_TO_CART"
export const SUBSTRACT_TO_CART = "SUBSTRACT_TO_CART"